# Model Notebook for Coding in SK-LEARN

In [30]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LinearRegression

In [31]:
# import the data
df = sns.load_dataset('tips')
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [32]:
# To this:
# # preprocess the data
scalar = StandardScaler()  # Move this line completely to the left margin
df[['total_bill', 'tip']] = scalar.fit_transform(df[['total_bill', 'tip']])


In [33]:
# # preprocess the data
scalar = StandardScaler()
df[['total_bill', 'tip']] = scalar.fit_transform(df[['total_bill', 'tip']])

In [34]:
# separate the features X and the target/labels y
X = df[['total_bill']]
y = df['tip']

In [35]:
X

,total_bill
0,-0.314711
1,-1.063235
2,0.137780
3,0.438315
4,0.540745
...,...
239,1.040511
240,0.832275
241,0.324630
242,-0.221287


In [36]:
y

0     -1.439947
1     -0.969205
2      0.363356
3      0.225754
4      0.443020
         ...   
239    2.115963
240   -0.722971
241   -0.722971
242   -0.904026
243    0.001247
Name: tip, Length: 244, dtype: float64

In [37]:
# train test split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [38]:
# call the model
model = LinearRegression()

In [39]:
# train the model
model.fit(X_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [40]:
model.predict([[15]])

c:\Users\Hair\AppData\Local\miniconda3\envs\python_ml\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.21970502])

In [41]:
# prediction
y_pred = model.predict(X_test)

In [42]:
y_pred

array([-0.36648619,  2.15494727,  0.41631932, -0.39109304,  1.61821029,
        0.9422908 , -0.33649659, -0.02506611, -0.48721356, -0.21807611,
       -0.63639261, -0.30266217, -0.22192093, -0.5894858 ,  0.61701896,
       -0.39263097, -0.51028249, -0.11042113, -0.75942687,  1.11376981,
       -0.13810384, -0.14271762, -0.65638568, -0.77326823, -0.35879655,
       -0.32034834,  0.20100936,  0.39478832, -0.05428674,  0.05798202,
       -0.67637875,  1.85735815,  0.75235665,  0.78849797, -0.41646886,
       -0.39493787,  0.01107521, -0.96781616, -0.28113117, -0.75404413,
       -0.46106878, -0.33342073,  0.39555729,  0.37325733,  0.23253689,
       -0.28805185, -0.10503838, -0.21961404, -0.31881041])

In [43]:
# evaluation the model
from sklearn.metrics import mean_squared_error, r2_score
print('MSE: ', mean_squared_error(y_test, y_pred))
print('R2: ', r2_score(y_test, y_pred))

MSE:  0.5026516242026468
R2:  0.4282707168319331


# Save and load a model

In [45]:
import os

# Create the folder if it does not exist
os.makedirs("./saved_models", exist_ok=True)

# Your original code will now work
import pickle

pickle.dump(model, open("./saved_models/model_01.pkl", "wb"))


In [47]:
# load the model
import pickle
model_load = pickle.load(open('./saved_models/model_01.pkl', 'rb'))

In [48]:
model_load.predict([[15]])

c:\Users\Hair\AppData\Local\miniconda3\envs\python_ml\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.21970502])